declare -A engines
engines=(
    ["🔎 Bing"]="https://www.bing.com/search?q="
    ["🔎 Google"]="https://www.google.com/search?q="
    ["🔎 Yahoo"]="https://search.yahoo.com/search?p="
    ["🛒 Amazon"]="https://www.amazon.ca/s?k="
    ["🔎 AUR"]="https://aur.archlinux.org/packages?O=0&K="
    ["JAV Guru (TUBE)"]="https://jav.guru/?s="
    ["iJavTorrent (TORRENT)"]="https://ijavtorrent.com/?searchTerm="
    ["OneJAV (TORRENT)"]="https://onejav.com/search/"
    ["ProjectJAV (TORRENT)"]="https://projectjav.com/?searchTerm="
    ["JAVAngel (TORRENT)"]="https://jav-angel.net/?s="
    ["📰 BBC"]="https://www.bbc.co.uk/search?q="
    ["📚 Stack Overflow"]="https://stackoverflow.com/search?q="
    ["📰 CNN"]="https://www.cnn.com/search?q="
    ["🛒 eBay"]="https://www.ebay.ca/sch/i.html?_nkw="
    ["💻 GitHub"]="https://github.com/search?q="
    ["🦆 DuckDuckGo"]="https://duckduckgo.com/?q="
    ["📷 Unsplash"]="https://unsplash.com/s/photos/"
    ["📸 Wallpaper Cave"]="https://wallpapercave.com/search?q="
    ["🌍 Wikipedia"]="https://en.wikipedia.org/wiki/Special:Search?search="
    ["📹 YouTube"]="https://www.youtube.com/results?search_query="
    ["👾 Reddit"]="https://www.reddit.com/search/?q="
    ["📰 Reuters"]="https://www.reuters.com/search/news?blob="
)
